force-app/main/default/objects/CAMS_Check__c/CAMS_Check__c.object-meta.xml
<CustomObject>
    <label>CAMS Queue</label>
    <nameField>
        <displayFormat>CAMS-{00000000}</displayFormat>
        <label>Unique Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CAMS Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CAMS_Check__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <formula>Application__r.genesis__Account__r.EIN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>CAMS Checks</relationshipLabel>
    <relationshipName>CAMS_Checks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/CAMS_PEP_Indicator__c.field-meta.xml
<CustomField>
    <fullName>CAMS_PEP_Indicator__c</fullName>
    <inlineHelpText>To clear a pep, the user needs to tell the system if the cams should be called with a pep indicator of true or false.</inlineHelpText>
    <label>CAMS PEP Indicator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>True</fullName>
            </value>
            <value>
                <fullName>False</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Confirmed_PEP__c.field-meta.xml
<CustomField>
    <fullName>Confirmed_PEP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Confirmed PEP?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Customer_LE_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_LE_Type__c</fullName>
    <defaultValue>&apos;PLC&apos;</defaultValue>
    <label>Customer LE Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Customer_LE_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <formula>Quick_Quote__r.genesis__Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consumer</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Distribution_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Channel__c</fullName>
    <defaultValue>&quot;face-to-face&quot;</defaultValue>
    <label>Distribution Channel</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Dll_Country__c.field-meta.xml
<CustomField>
    <fullName>Dll_Country__c</fullName>
    <defaultValue>&#39;W&#39;</defaultValue>
    <label>Dll Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>DSM</fullName>
            </value>
            <value>
                <fullName>W</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Geography__c.field-meta.xml
<CustomField>
    <fullName>Geography__c</fullName>
    <defaultValue>&apos;US&apos;</defaultValue>
    <label>Geography</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>US</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Lease_Signer_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Lease_Signer_First_Name__c</fullName>
    <formula>Application__r.Contract_Signer__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lease Signer First Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Lease_Signer_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Lease_Signer_Last_Name__c</fullName>
    <formula>Application__r.Contract_Signer_Last_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lease Signer Last Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Lease_Signer_Title__c.field-meta.xml
<CustomField>
    <fullName>Lease_Signer_Title__c</fullName>
    <formula>Application__r.Contract_Signer_Title__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lease Signer Title</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/LS_Contract__c.field-meta.xml
<CustomField>
    <fullName>LS_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LS Contract</label>
    <referenceTo>cllease__Lease_Account__c</referenceTo>
    <relationshipLabel>CAMS Checks</relationshipLabel>
    <relationshipName>CAMS_Checks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Missing_Data__c.field-meta.xml
<CustomField>
    <fullName>Missing_Data__c</fullName>
    <formula>or(isBLANK(Account_Number__c),isblank(  Application__c),  isblank( TEXT(Customer_LE_Type__c) ), isblank( Customer_Name__c),  isblank( TExt(Customer_Type__c) ), isblank( Distribution_Channel__c),  isblank( text(Dll_Country__c)),  isblank(text(Geography__c)),  isblank( Lease_Signer_First_Name__c),  isblank( Lease_Signer_Last_Name__c),  isblank( Lease_Signer_Title__c),  isblank( NAICS__c),    isblank( Source_System__c),  isblank( Transaction_Amount__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Missing Data</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/NAICS__c.field-meta.xml
<CustomField>
    <fullName>NAICS__c</fullName>
    <label>NAICS</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Publicly_Traded__c.field-meta.xml
<CustomField>
    <fullName>Publicly_Traded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Publicly Traded?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Publicly_Traded_Full_Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Publicly_Traded_Full_Subsidiary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Publicly Traded Full Subsidiary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Quick_Quote__c.field-meta.xml
<CustomField>
    <fullName>Quick_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quick Quote</label>
    <referenceTo>genesis__Quick_Quotes__c</referenceTo>
    <relationshipLabel>CAMS Checks</relationshipLabel>
    <relationshipName>CAMS_Checks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Response_Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Response_Case_Number__c</fullName>
    <label>Response Case Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Response_Diligence__c.field-meta.xml
<CustomField>
    <fullName>Response_Diligence__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Response Diligence</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Response_Risk_Rating__c.field-meta.xml
<CustomField>
    <fullName>Response_Risk_Rating__c</fullName>
    <label>Response Risk Rating</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <defaultValue>&quot;CLND&quot;</defaultValue>
    <label>Source System</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Auto Cleared</fullName>
            </value>
            <value>
                <fullName>Held - Medium</fullName>
            </value>
            <value>
                <fullName>Held - High</fullName>
            </value>
            <value>
                <fullName>Held - Data Issue</fullName>
            </value>
            <value>
                <fullName>Manually Cleared</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Transaction_Amount__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Amount__c</fullName>
    <formula>Application__r.genesis__Financed_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Transaction Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Trust__c.field-meta.xml
<CustomField>
    <fullName>Trust__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Trust?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CD_CAMSController.cls
/***********************************************************************************************************************
*
* change log:
*
* 9/26/19- MRM - Created
  10/11/19 - MRM - added pep clear 
*
*
*
*************************************************************************************************************************/
global with sharing class CD_CAMSController {
	public static final String RESPONSE_KEYWORD_STATUS = 'Status';
    public static final String RESPONSE_KEYWORD_MESSAGE = 'Message';
    public static final String STATUS_ERROR = 'ERROR';
    public static final String STATUS_SUCCESS = 'SUCCESS';
    
 
     @AuraEnabled
     /******************************************************************************************
    * CLEAR
    *******************************************************************************************/
    public static String clear(Id camsCheckId){
    	
    	Map<String,String> response = new Map<String,String>();
    	
        CAMS_Check__c cc = [SELECT Account_Number__c
                                    ,Application__c
                                    ,Confirmed_PEP__c
                                    ,Customer_LE_Type__c
                                    ,Customer_Name__c
                                    ,Customer_Type__c
                                    ,Distribution_Channel__c
                                    ,Dll_Country__c
                                    ,Geography__c
                                    ,Lease_Signer_First_Name__c
                                    ,Lease_Signer_Last_Name__c
                                    ,Lease_Signer_Title__c
                                    ,LS_Contract__c
                                    ,NAICS__c
                                    ,Name
                                    ,OwnerId
                                    ,Publicly_Traded_Full_Subsidiary__c
                                    ,Publicly_Traded__c
                                    ,Quick_Quote__c
                                    ,Response_Case_Number__c
                                    ,Response_Diligence__c
                                    ,Response_Risk_Rating__c
                                    ,Source_System__c
                                    ,Status__c
                                    ,Transaction_Amount__c
                                    ,Trust__c 
                                    ,missing_data__c
                                    FROM CAMS_Check__c
                     		        where id = :camsCheckId
							        ];

        if (!cc.status__c.contains('Held - High') && !cc.status__c.contains('Held - Medium') ){
    		response.put(RESPONSE_KEYWORD_MESSAGE,'The status must be held H/M to perform a clear!');
            return JSON.serialize(response);
        }

        
    	
        Map<ID,String> applicationMap = new Map<ID,String>();
        applicationMap.put(cc.Application__c,'Clear');

    	CAMSUtility.callCAMS(applicationMap);
		
    	return JSON.serialize(response);
    }

    @AuraEnabled
     /******************************************************************************************
    * RESUBMIT
    *******************************************************************************************/
    public static String resubmit(Id camsCheckId){
    	
    	Map<String,String> response = new Map<String,String>();
    	
        CAMS_Check__c cc = [SELECT Account_Number__c
                                    ,Application__c
                                    ,Confirmed_PEP__c
                                    ,Customer_LE_Type__c
                                    ,Customer_Name__c
                                    ,Customer_Type__c
                                    ,Distribution_Channel__c
                                    ,Dll_Country__c
                                    ,Geography__c
                                    ,Lease_Signer_First_Name__c
                                    ,Lease_Signer_Last_Name__c
                                    ,Lease_Signer_Title__c
                                    ,LS_Contract__c
                                    ,NAICS__c
                                    ,Name
                                    ,OwnerId
                                    ,Publicly_Traded_Full_Subsidiary__c
                                    ,Publicly_Traded__c
                                    ,Quick_Quote__c
                                    ,Response_Case_Number__c
                                    ,Response_Diligence__c
                                    ,Response_Risk_Rating__c
                                    ,Source_System__c
                                    ,Status__c
                                    ,Transaction_Amount__c
                                    ,Trust__c 
                                    ,missing_data__c
                                    FROM CAMS_Check__c
                     		        where id = :camsCheckId
							        ];

        if (!cc.status__c.contains('Held - Data Issue')){
    		response.put(RESPONSE_KEYWORD_MESSAGE,'The status must be Held - Data Issue to resubmit!');
            return JSON.serialize(response);
        }

        if (cc.missing_data__c == true){
    		response.put(RESPONSE_KEYWORD_MESSAGE,'To resubmit, all fields must be filled in!');
            return JSON.serialize(response);
        }
    	
        Map<ID,String> applicationMap = new Map<ID,String>();
        applicationMap.put(cc.Application__c,'Resubmit');

    	CAMSUtility.callCAMS(applicationMap);
		
    	return JSON.serialize(response);
    }
    
    @AuraEnabled
     /******************************************************************************************
    * PEP CLEAR
    *******************************************************************************************/
    public static String pepClear(Id camsCheckId, Cams_check__c cams){
    	
        Map<String,String> response = new Map<String,String>();
    	
        CAMS_Check__c cc = [SELECT Account_Number__c
                                    ,Application__c
                                    ,Confirmed_PEP__c
                                    ,Customer_LE_Type__c
                                    ,Customer_Name__c
                                    ,Customer_Type__c
                                    ,Distribution_Channel__c
                                    ,Dll_Country__c
                                    ,Geography__c
                                    ,Lease_Signer_First_Name__c
                                    ,Lease_Signer_Last_Name__c
                                    ,Lease_Signer_Title__c
                                    ,LS_Contract__c
                                    ,NAICS__c
                                    ,Name
                                    ,OwnerId
                                    ,Publicly_Traded_Full_Subsidiary__c
                                    ,Publicly_Traded__c
                                    ,Quick_Quote__c
                                    ,CAMS_PEP_Indicator__c
                                    ,Response_Case_Number__c
                                    ,Response_Diligence__c
                                    ,Response_Risk_Rating__c
                                    ,Source_System__c
                                    ,Status__c
                                    ,Transaction_Amount__c
                                    ,Trust__c 
                                    ,missing_data__c
                                    FROM CAMS_Check__c
                     		        where id = :camsCheckId
							        ];

        if (!cc.status__c.contains('Held - PEP Hit')){
    		response.put(RESPONSE_KEYWORD_MESSAGE,'The status must be Held - PEP Hit to clear pep hit!');
            return JSON.serialize(response);
        }

        if (cc.missing_data__c == true){
    		response.put(RESPONSE_KEYWORD_MESSAGE,'To clear pep, all fields must be filled in!');
            return JSON.serialize(response);
        }
    	
        if (cams.CAMS_PEP_Indicator__c == 'True'|| cams.CAMS_PEP_Indicator__c == 'False' )
            integer doNothing;
        else{
    		response.put(RESPONSE_KEYWORD_MESSAGE,'A pep choice is required!');
            return JSON.serialize(response);
        }

        genesis__Applications__c a = [select id 
                                    from genesis__Applications__c 
                                    where id = :cc.Application__c
        ];

        a.genesis__status__c = 'CREDIT APPROVED';
        if (cams.CAMS_PEP_Indicator__c == 'True')
            cc.confirmed_pep__c = true;
        else {
            cc.confirmed_pep__c = false;
        }
        
        cc.cams_pep_indicator__c = null;
        
        cc.status__c = 'Manually Cleared OFAC PEP';

        update a;
        update cc;        

    	return JSON.serialize(response);
    }

    @AuraEnabled
    /******************************************************************************************
    * RETURN LIST VIEW ID FOR CAMS CHECK
    *******************************************************************************************/
    public static List<ListView> getListViews() {
        
        List<ListView> listviews =
            [SELECT Id, Name FROM ListView WHERE SobjectType = 'CAMS_Check__c'];

        return listviews;
    }
}