force-app/main/default/objects/CAMS_Check__c/CAMS_Check__c.object-meta.xml
<CustomObject>
    <label>CAMS Queue</label>
    <nameField>
        <displayFormat>CAMS-{00000000}</displayFormat>
        <label>Unique Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CAMS Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CAMS_Check__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <formula>Application__r.genesis__Account__r.EIN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>CAMS Checks</relationshipLabel>
    <relationshipName>CAMS_Checks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Confirmed_PEP__c.field-meta.xml
<CustomField>
    <fullName>Confirmed_PEP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Confirmed PEP?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Customer_LE_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_LE_Type__c</fullName>
    <defaultValue>&apos;PLC&apos;</defaultValue>
    <label>Customer LE Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Customer_LE_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <formula>Quick_Quote__r.genesis__Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consumer</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Distribution_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Channel__c</fullName>
    <defaultValue>&quot;face-to-face&quot;</defaultValue>
    <label>Distribution Channel</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Dll_Country__c.field-meta.xml
<CustomField>
    <fullName>Dll_Country__c</fullName>
    <defaultValue>&#39;W&#39;</defaultValue>
    <label>Dll Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>DSM</fullName>
            </value>
            <value>
                <fullName>W</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Geography__c.field-meta.xml
<CustomField>
    <fullName>Geography__c</fullName>
    <defaultValue>&apos;US&apos;</defaultValue>
    <label>Geography</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>US</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Lease_Signer_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Lease_Signer_First_Name__c</fullName>
    <formula>Application__r.Contract_Signer__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lease Signer First Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Lease_Signer_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Lease_Signer_Last_Name__c</fullName>
    <formula>Application__r.Contract_Signer_Last_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lease Signer Last Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Lease_Signer_Title__c.field-meta.xml
<CustomField>
    <fullName>Lease_Signer_Title__c</fullName>
    <formula>Application__r.Contract_Signer_Title__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lease Signer Title</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/LS_Contract__c.field-meta.xml
<CustomField>
    <fullName>LS_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LS Contract</label>
    <referenceTo>cllease__Lease_Account__c</referenceTo>
    <relationshipLabel>CAMS Checks</relationshipLabel>
    <relationshipName>CAMS_Checks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Missing_Data__c.field-meta.xml
<CustomField>
    <fullName>Missing_Data__c</fullName>
    <formula>or(isBLANK(Account_Number__c),isblank(  Application__c),  isblank( TEXT(Customer_LE_Type__c) ), isblank( Customer_Name__c),  isblank( TExt(Customer_Type__c) ), isblank( Distribution_Channel__c),  isblank( text(Dll_Country__c)),  isblank(text(Geography__c)),  isblank( Lease_Signer_First_Name__c),  isblank( Lease_Signer_Last_Name__c),  isblank( Lease_Signer_Title__c),  isblank( NAICS__c),    isblank( Source_System__c),  isblank( Transaction_Amount__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Missing Data</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/NAICS__c.field-meta.xml
<CustomField>
    <fullName>NAICS__c</fullName>
    <label>NAICS</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Product_Risk__c.field-meta.xml
<CustomField>
    <fullName>Product_Risk__c</fullName>
    <defaultValue>&#39;Lease&#39;</defaultValue>
    <label>Product Risk</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SLB</fullName>
            </value>
            <value>
                <fullName>Lease</fullName>
            </value>
            <value>
                <fullName>Asset Sale</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Publicly_Traded__c.field-meta.xml
<CustomField>
    <fullName>Publicly_Traded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Publicly Traded?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Publicly_Traded_Full_Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Publicly_Traded_Full_Subsidiary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Publicly Traded Full Subsidiary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Quick_Quote__c.field-meta.xml
<CustomField>
    <fullName>Quick_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quick Quote</label>
    <referenceTo>genesis__Quick_Quotes__c</referenceTo>
    <relationshipLabel>CAMS Checks</relationshipLabel>
    <relationshipName>CAMS_Checks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Response_Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Response_Case_Number__c</fullName>
    <label>Response Case Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Response_Diligence__c.field-meta.xml
<CustomField>
    <fullName>Response_Diligence__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Response Diligence</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Response_Risk_Rating__c.field-meta.xml
<CustomField>
    <fullName>Response_Risk_Rating__c</fullName>
    <label>Response Risk Rating</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <defaultValue>&quot;CLND&quot;</defaultValue>
    <label>Source System</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Auto Cleared</fullName>
            </value>
            <value>
                <fullName>Held - Medium</fullName>
            </value>
            <value>
                <fullName>Held - High</fullName>
            </value>
            <value>
                <fullName>Held - Data Issue</fullName>
            </value>
            <value>
                <fullName>Manually Cleared</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Transaction_Amount__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Amount__c</fullName>
    <formula>Application__r.genesis__Financed_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Transaction Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Trust__c.field-meta.xml
<CustomField>
    <fullName>Trust__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Trust?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OFAC_Log__c/OFAC_Log__c.object-meta.xml
<CustomObject>
    <label>OFAC Log</label>
    <nameField>
        <displayFormat>OFAC-{00000000}</displayFormat>
        <label>OFAC Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OFAC Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/OFACCall.cls
/*******************************************************************************************************************
*   OFACCall - made this into a queable since cams need to be called in sequence
* 
*	Change Log: 
*	9/25/19 - MRM Created
*   10/14/19 - MRM added call to cams
* 
********************************************************************************************************************/
public class OFACCall implements Queueable, Database.AllowsCallouts {
    
    
    private Map<ID,String> applicationMap;

    public  OFACCall(Map<ID,String> applicationMap)
    {
        this.applicationMap = applicationMap;
    }
    
    public void execute(QueueableContext context) {
    	
    	genesis__Applications__c app = new genesis__applications__c(); 
    	Bridger.bridgerInput input1 = new Bridger.bridgerInput();
    	Bridger.bridgerInput input2 = new Bridger.bridgerInput();
		Bridger.bridgerInput input3 = new Bridger.bridgerInput();
    	Boolean businessHit = false;
    	Boolean individualHit = false;
		Boolean pepHit = false;
    	bridger.bridgerResult IndividualResult = new Bridger.bridgerResult();
        bridger.bridgerResult businessResult = new Bridger.bridgerResult();
		bridger.bridgerResult pepResult = new Bridger.bridgerResult();
    	
    	try{
			
    		app = [select genesis__account__r.name
    					,billing_address1__r.address_line_1__c
    					,billing_address1__r.address_line_2__c
    					,billing_address1__r.city__c
    					,billing_address1__r.county__c
    					,billing_address1__r.country__c
    					,billing_address1__r.zip_code__c
    					,billing_address1__r.state__c
    					,genesis__account__r.EIN__c
    					,contract_signer__c
    					,contract_signer_last_name__c
    					,contract_signer_title__c
						,genesis__Status__c
    				from genesis__applications__c
    				where id in :applicationMap.keySet()
    				limit 1	
    		];

			if (app.genesis__Status__c <> 'OFAC APPROVED'){
			 
    			/* business */
    			input1.requestType = 'Business'; 
    			input1.street1 = app.billing_address1__r.address_line_1__c;
    			input1.street2 = app.billing_address1__r.address_line_2__c;
    			input1.city = app.billing_address1__r.city__c;
    			input1.stateprovincedistrict = app.billing_address1__r.state__c;
    			input1.postalcode = app.billing_address1__r.zip_code__c;
    			input1.addresstype = 'Current';
    			input1.county = app.billing_address1__r.county__c;
    			input1.fullname = app.genesis__account__r.name;
    			input1.ein = app.genesis__account__r.ein__c;  
    		 
    			system.debug('************ input1: ' + input1);
    			/* individual */
    			input2.requestType = 'Individual';
    			input2.title = app.Contract_Signer_Title__c;
    			input2.last = app.contract_signer_last_name__c;
    			input2.first = app.contract_signer__c;
    			system.debug('************ input2: ' + input2);
    		
    		
    			businessResult = bridger.bridgerSearch(input1,false);//business
    			individualResult = bridger.bridgerSearch(input2,false);//individual

				if (!businessResult.hit && !individualResult.hit){
					if (system.label.cams_check == 'True'){
						pepResult = bridger.bridgerSearch(input1,true);//pep 
					}
				}

				NewCoUtility.skipApplicationTrigger = true;
				
				if (businessResult.hit || individualResult.hit){
	   				app.genesis__Status__c = 'OFAC DECLINED';
				}
    			else{
					if (pepResult.hit != null){
						if (pepResult.hit){
							app.genesis__Status__c = 'OFAC DECLINED - PEP';
						}
						else
    						app.genesis__Status__c = 'OFAC APPROVED';
					}
					else {
						app.genesis__Status__c = 'OFAC APPROVED';
					}
				}
    			update app;

			}
			CAMS_Check__c cc;
			
			if (system.label.cams_check == 'True'){
				List<CAMS_Check__c> ccList = [SELECT Account_Number__c
                                    ,Application__c
                                    ,Application__r.name
                                    ,Confirmed_PEP__c
                                    ,Customer_LE_Type__c
                                    ,Customer_Name__c
                                    ,Product_Risk__c
                                    ,Customer_Type__c
                                    ,Distribution_Channel__c
                                    ,Dll_Country__c
                                    ,Geography__c
                                    ,Lease_Signer_First_Name__c
                                    ,Lease_Signer_Last_Name__c
                                    ,Lease_Signer_Title__c
                                    ,LS_Contract__c
                                    ,NAICS__c 
                                    ,Name
                                    ,OwnerId
                                    ,Publicly_Traded_Full_Subsidiary__c
                                    ,Publicly_Traded__c
                                    ,Quick_Quote__c
                                    ,Response_Case_Number__c
                                    ,Response_Diligence__c
                                    ,Response_Risk_Rating__c
                                    ,Source_System__c
                                    ,Status__c
                                    ,Transaction_Amount__c
                                    ,Trust__c 
                                    ,missing_data__c
                                    FROM CAMS_Check__c
                     		        where application__c in :applicationMap.keySet()
							        ];
				if (ccList.size() == 0){
       				cc = CAMSUtility.createCamsCheckRecord(applicationMap,'CAMS CHECK',individualResult.hit);
				}
				else
					cc = ccList[0];
			}
			system.debug('app status is:' + app.genesis__status__c);

			if (app.genesis__Status__c == 'OFAC APPROVED' && system.label.cams_check == 'True'){
				system.debug('Submitting CAMS Call now.....');
            	CAMSCall job = new CAMSCall(applicationMap);
        		System.enqueueJob(job);	   
			}
	
			if (app.genesis__Status__c == 'OFAC DECLINED - PEP'){
				cc.status__c = 'Held - PEP Hit';
				update cc;
			}
			 
    	}
    	catch (Exception e){
    		system.debug('***** Exception: ' + e);
    		ofac_log__c o1 = new ofac_log__c();
    		o1.result__c = string.valueOf(e);
    		o1.application__c = app.id;
			insert o1;
			
			app.genesis__Status__c = 'OFAC FATAL';
    		NewCoUtility.skipApplicationTrigger = true;
    		update app;
			    		
    	}	
    	finally {
    		system.debug(app.billing_address1__r.address_line_1__c);
			List<OFAC_Log__c> oList = new List<OFAC_Log__c>();
			
			system.debug(input1);
			ofac_log__c o1 = new ofac_log__c();
    		o1.input__c = string.valueOf(input1);
    		o1.application__c = app.id;
    		o1.result__c =  businessResult.result;
    		olist.add(o1);
			
			system.debug(input2);
			ofac_log__c o2 = new ofac_log__c();
    		o2.input__c = string.valueOf(input2);
    		o2.result__c = individualResult.result;
    		o2.application__c = app.id;
    		oList.add(o2);
    		
			if (!olist.isEmpty())
				insert oList;
    	} 
    	
    }

}