force-app/main/default/objects/CAMS_Check__c/CAMS_Check__c.object-meta.xml
<CustomObject>
    <label>CAMS Queue</label>
    <nameField>
        <displayFormat>CAMS-{00000000}</displayFormat>
        <label>Unique Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CAMS Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CAMS_Check__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <formula>Application__r.genesis__Account__r.EIN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>genesis__Applications__c</referenceTo>
    <relationshipLabel>CAMS Checks</relationshipLabel>
    <relationshipName>CAMS_Checks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Confirmed_PEP__c.field-meta.xml
<CustomField>
    <fullName>Confirmed_PEP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Confirmed PEP?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Customer_LE_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_LE_Type__c</fullName>
    <defaultValue>&apos;PLC&apos;</defaultValue>
    <label>Customer LE Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Customer_LE_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <formula>Quick_Quote__r.genesis__Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consumer</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Distribution_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Channel__c</fullName>
    <defaultValue>&quot;face-to-face&quot;</defaultValue>
    <label>Distribution Channel</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Dll_Country__c.field-meta.xml
<CustomField>
    <fullName>Dll_Country__c</fullName>
    <defaultValue>&#39;W&#39;</defaultValue>
    <label>Dll Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>DSM</fullName>
            </value>
            <value>
                <fullName>W</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Geography__c.field-meta.xml
<CustomField>
    <fullName>Geography__c</fullName>
    <defaultValue>&apos;US&apos;</defaultValue>
    <label>Geography</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>US</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Lease_Signer_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Lease_Signer_First_Name__c</fullName>
    <formula>Application__r.Contract_Signer__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lease Signer First Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Lease_Signer_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Lease_Signer_Last_Name__c</fullName>
    <formula>Application__r.Contract_Signer_Last_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lease Signer Last Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Lease_Signer_Title__c.field-meta.xml
<CustomField>
    <fullName>Lease_Signer_Title__c</fullName>
    <formula>Application__r.Contract_Signer_Title__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lease Signer Title</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/LS_Contract__c.field-meta.xml
<CustomField>
    <fullName>LS_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LS Contract</label>
    <referenceTo>cllease__Lease_Account__c</referenceTo>
    <relationshipLabel>CAMS Checks</relationshipLabel>
    <relationshipName>CAMS_Checks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Missing_Data__c.field-meta.xml
<CustomField>
    <fullName>Missing_Data__c</fullName>
    <formula>or(isBLANK(Account_Number__c),isblank(  Application__c),  isblank( TEXT(Customer_LE_Type__c) ), isblank( Customer_Name__c),  isblank( TExt(Customer_Type__c) ), isblank( Distribution_Channel__c),  isblank( text(Dll_Country__c)),  isblank(text(Geography__c)),  isblank( Lease_Signer_First_Name__c),  isblank( Lease_Signer_Last_Name__c),  isblank( Lease_Signer_Title__c),  isblank( NAICS__c),    isblank( Source_System__c),  isblank( Transaction_Amount__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Missing Data</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/NAICS__c.field-meta.xml
<CustomField>
    <fullName>NAICS__c</fullName>
    <label>NAICS</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Product_Risk__c.field-meta.xml
<CustomField>
    <fullName>Product_Risk__c</fullName>
    <defaultValue>&#39;Lease&#39;</defaultValue>
    <label>Product Risk</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SLB</fullName>
            </value>
            <value>
                <fullName>Lease</fullName>
            </value>
            <value>
                <fullName>Asset Sale</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Publicly_Traded__c.field-meta.xml
<CustomField>
    <fullName>Publicly_Traded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Publicly Traded?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Publicly_Traded_Full_Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Publicly_Traded_Full_Subsidiary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Publicly Traded Full Subsidiary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Quick_Quote__c.field-meta.xml
<CustomField>
    <fullName>Quick_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quick Quote</label>
    <referenceTo>genesis__Quick_Quotes__c</referenceTo>
    <relationshipLabel>CAMS Checks</relationshipLabel>
    <relationshipName>CAMS_Checks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Response_Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Response_Case_Number__c</fullName>
    <label>Response Case Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Response_Code__c.field-meta.xml
<CustomField>
    <fullName>Response_Code__c</fullName>
    <label>Response Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Response_Diligence__c.field-meta.xml
<CustomField>
    <fullName>Response_Diligence__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Response Diligence</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Response_Risk_Rating__c.field-meta.xml
<CustomField>
    <fullName>Response_Risk_Rating__c</fullName>
    <label>Response Risk Rating</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <defaultValue>&quot;CLND&quot;</defaultValue>
    <label>Source System</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Auto Cleared</fullName>
            </value>
            <value>
                <fullName>Held - Medium</fullName>
            </value>
            <value>
                <fullName>Held - High</fullName>
            </value>
            <value>
                <fullName>Held - Data Issue</fullName>
            </value>
            <value>
                <fullName>Manually Cleared</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Transaction_Amount__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Amount__c</fullName>
    <formula>Application__r.genesis__Financed_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Transaction Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CAMS_Check__c/fields/Trust__c.field-meta.xml
<CustomField>
    <fullName>Trust__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Trust?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CAMSUtility.cls
/*********************************************************************************************
*
* CAMS Utility Class - used for cams calls
*
* Change Log:
*
* 9/24/19 - MRM created
* 9/22/2020 - MRM new fields assetType and crossBorder
*
**********************************************************************************************/
global without sharing class CAMSUtility { 
    
    public static Boolean skipApplicationTrigger = false;
    
    /*************************************************************************************************
    * 
    * Data Structure to hold cams results
    *
    *************************************************************************************************/
    //{"code":"200","statusDesc":"Success","caseNumber":"","dueDiligenceComplete":"false","riskRating":""}
    public class results{
       
       public String code;
       public String statusDesc;
       public String caseNumber;
       public String dueDiligenceComplete;
       public String riskRating;
   
    }
    /*************************************************************************************************
    * 
    * Cams Callout
    *
    *************************************************************************************************/
    public static void callCAMS(Map<ID,String> applicationMap){

        ID appId;

        for (ID s:applicationMap.keySet())
            appId = s;

        //call cams here

        genesis__Applications__c a = [select id
                                     ,genesis__Status__c
                                     from genesis__Applications__c
                                     where id = :appId
                                     ];

       
        system.debug('status is: ' + a.genesis__status__c);

       
        List<CAMS_Check__c> ccList = [SELECT Account_Number__c
                                    ,Application__c
                                    ,Application__r.name
                                    ,Confirmed_PEP__c
                                    ,Customer_LE_Type__c
                                    ,Customer_Name__c
                                    ,Product_Risk__c
                                    ,Customer_Type__c
                                    ,Distribution_Channel__c
                                    ,Dll_Country__c
                                    ,Geography__c
                                    ,Lease_Signer_First_Name__c
                                    ,Lease_Signer_Last_Name__c
                                    ,Lease_Signer_Title__c
                                    ,LS_Contract__c
                                    ,NAICS__c
                                    ,Name
                                    ,OwnerId
                                    ,Publicly_Traded_Full_Subsidiary__c
                                    ,Publicly_Traded__c
                                    ,Quick_Quote__c
                                    ,Response_Case_Number__c
                                    ,Response_Diligence__c
                                    ,Response_Risk_Rating__c
                                    ,Source_System__c
                                    ,Status__c
                                    ,Transaction_Amount__c
                                    ,Trust__c 
                                    ,missing_data__c
                                    FROM CAMS_Check__c
                                    where application__c = :appId
                                    ];

        CAMS_Check__c cc;

        if (ccList.size() == 0){
            cc = CAMSUtility.createCamsCheckRecord(applicationMap,'CAMS CHECK',false);
        }
        else{
            cc = ccList[0];
        }

        
        /*
        if (cc.missing_data__c){
            cc.status__c = 'Held - Data Issue';
            a.genesis__status__c = 'CAMS REFERRED';
            update a;
            update cc;
            return;
        }
        */ 

        HttpRequest reqAPI = new HttpRequest();  
            
        reqAPI.setEndpoint(System.Label.CAMS_Endpoint);
        reqAPI.setMethod('POST');          
        reqAPI.setHeader('Authorization', 'Bearer '+ ICVUtility.getAccessToken());
        reqAPI.setHeader('content-type', 'application/json');
        reqAPI.setTimeout(120000);
            
        JSONGenerator gen = JSON.createGenerator(true);
            
        gen.writeStartObject();
        if (cc.Account_Number__c == null)
            gen.writeNullField('customerID');
        else
            gen.writeStringField('customerID', cc.Account_Number__c);

        if(cc.Geography__c == null)
            gen.writeNullField('geography');
        else
            gen.writeStringField('geography', cc.Geography__c);

        if (cc.Customer_LE_Type__c == null)    
            gen.writeNullField('customerLEType');
        else
            gen.writeStringField('customerLEType', cc.Customer_LE_Type__c);
        
        if (cc.NAICS__c == null)
            gen.writeNullField('NAICScode');
        else
            gen.writeStringField('NAICScode', cc.NAICS__c);

        if (cc.Distribution_Channel__c == null)
            gen.writeNullField('distributionChannel');
        else
            gen.writeStringField('distributionChannel', cc.Distribution_Channel__c);

        if (cc.product_risk__c == null)   
            gen.writeNullField('productRisk');  
        else
            gen.writeStringField('productRisk', cc.product_risk__c);

        if (cc.Confirmed_PEP__c == null)
            gen.writeNullField('confirmedPEP');
        else
            gen.writeStringField('confirmedPEP', string.valueOf(cc.Confirmed_PEP__c));
         
        gen.writeStringField('applicationNumber', cc.Application__r.name);
        gen.writeStringField('sourceSystem', cc.Source_System__c);
        gen.writeStringField('transactionAmount', string.valueOf(cc.Transaction_Amount__c));

        if (cc.Customer_Name__c != null)
            gen.writeStringField('customerName', cc.Customer_Name__c);
    
        if (cc.lease_signer_title__c != null)
            gen.writeStringField('leaseSignerTitle', cc.Lease_Signer_Title__c);
        if (cc.Lease_Signer_First_Name__c != null)
            gen.writeStringField('leaseSignerFirstName', cc.Lease_Signer_First_Name__c);
        if (cc.Lease_Signer_Last_Name__c != null)
            gen.writeStringField('leaseSignerLastName', cc.Lease_Signer_Last_Name__c);

        if (cc.Customer_Type__c == null)
            gen.writeNullField('customerType');
        else
            gen.writeStringField('customerType', cc.Customer_Type__c);
        
        gen.writeStringField('DLLCountry', cc.Dll_Country__c);
        
        //Hi Everyone, here are the NAICS code that will indicate the customer being a trust. So the mid office systems (or back office system scripts for one time load customer extract) can check for this to send the appropriate value for trust indicator. This logic should be used for on going CRR call and to populate the value for this field for the One time load file. 

        //If NAICS code for the customer is one of the below then the Trust indicator will be a Y otherwise N.

        //The final list of trust NAICS codes are as follows:

        //523991 - Trust, Fiduciary, and Custody Activities
        //525920 - Trusts, Estates, and Agency Accounts
        //813211 - Grantmaking Foundations

        if (cc.NAICS__c == '523991' || cc.NAICS__c == '525920' || cc.NAICS__c == '813211' ) 
            cc.Trust__c = true;
        
        gen.writeStringField('trustIndicator', string.valueOf(cc.Trust__c));
        
        
        
        gen.writeStringField('publiclyTradedIndicator', string.valueOf(cc.Publicly_Traded__c));
        gen.writeStringField('publiclyTradedFullSubsidiary', string.valueOf(cc.Publicly_Traded_Full_Subsidiary__c));

        // new fields 9/22/2020
        gen.writeStringField('assetType', 'Other');
        gen.writeStringField('crossBorder', 'No');
        
        gen.writeEndObject();
        
        String jsonS = gen.getAsString();
        system.debug('json:' + jsonS);
        reqAPI.setBody(jsonS);  
        Http http1 = new Http();

        if (test.isRunningTest())
            return;
        HTTPResponse res1 = http1.send(reqAPI); 
        
        
        if (res1.getStatusCode() != 200){
            a.genesis__status__c = 'CAMS FATAL';  
            update a;
            return;
        }
        
        
        CAMSUtility.results res = (CAMSUtility.results) System.JSON.deserialize(res1.getBody(),CAMSUtility.results.class);  
        system.debug('result: ' + res);
        
        if (res.code == '200'){
            cc.Response_Risk_Rating__c = res.riskRating;
            cc.response_case_number__c = res.caseNumber;
            cc.response_diligence__c = boolean.valueOf(res.dueDiligenceComplete);
        }
        else{
            if (res.code.startsWith('4')){
                cc.status__c = 'Held - Data Issue';
                a.genesis__status__c = 'CAMS DEFERRED'; 
                update a;
                update cc;  
                return;
            }
            else{
                a.genesis__status__c = 'CAMS FATAL';  
                update a;
                return;
            }
        }

        cc.Response_Risk_Rating__c = res.riskRating;
        cc.response_case_number__c = res.caseNumber;
        cc.response_diligence__c =  boolean.valueOf(res.dueDiligenceComplete);
        cc.response_code__c = res.code;
        

        /* make the call here */

        if (cc.missing_data__c){
            cc.status__c = 'Held - Data Issue';
            a.genesis__status__c = 'CAMS REFERRED';
        }

        if (cc.response_risk_rating__c == 'H'){
            cc.status__c = 'Held - High';
            a.genesis__status__c = 'CAMS REFERRED';
        }
        else
        if (cc.response_risk_rating__c == 'M'){
             cc.status__c = 'Held - Medium';
             a.genesis__status__c = 'CAMS REFERRED';
        }
        else
        if (cc.response_risk_rating__c == 'L'){
            cc.status__c = 'Auto Cleared';
            a.genesis__status__c = 'CAMS APPROVED';
        }

        if (applicationMap.get(appId) == 'Clear' && cc.Response_Diligence__c == true){   
            cc.status__c = 'Manually Cleared';
            a.genesis__status__c = 'CAMS APPROVED';   
        }

        update a;
        update cc; 
        

        
    }

    /*************************************************************************************************
    * 
    * Cams Update Applciation Status
        *
    *************************************************************************************************/
    
    public static void updateApplicationStatus(Map<String,String> applicationMap){

        String appId;
        skipApplicationTrigger = true;

        for(String s:applicationMap.keySet())
            appId = s;

        genesis__Applications__c a = [select id
                                     ,genesis__Status__c
                                     from genesis__Applications__c
                                     where id = :appId
                                     ];
        a.genesis__Status__c = applicationMap.get(appId);

        update a;
    }



    /*************************************************************************************************
    * 
    * Cams Check Record 
    *
    *************************************************************************************************/
    public static CAMS_Check__c createCamsCheckRecord(Map<ID,String> applicationMap, String status, Boolean pep){
        String result;
        
        CAMS_Check__c cc;
        String applicationId;
        system.debug('application map is: ' + applicationMap);
        
        for (ID cId:applicationMap.keySet()){
            applicationId = cId;
        }
        
        genesis__Applications__c a = [select genesis__Quick_Quote__c
                                     ,genesis__account__r.naics__c
                                     from genesis__Applications__c
                                     where id = :applicationId
                                     ];

        List<CAMS_Check__c> ccList = [select id 
                            from CAMS_Check__c 
                            where application__c in :applicationMap.keySet()
                            ];
        
        if (ccList.size() != 0)
            cc = ccList[0];
        else{   
            cc = new CAMS_Check__c();
            cc.application__c = applicationId;
            cc.quick_quote__c = a.genesis__Quick_Quote__c;
            cc.geography__c = 'US';
            cc.dll_country__c = 'W';
            cc.customer_type__c = 'Commercial';
            cc.Confirmed_PEP__c = pep;
            cc.naics__c = a.genesis__account__r.naics__c;
        }

        cc.status__c = status.trim();

    

        upsert cc;

        return cc;

        
    }

}