force-app/main/default/objects/Int_PX_Remit__c/Int_PX_Remit__c.object-meta.xml
<CustomObject>
    <description>This contains payments received from PNC</description>
    <label>Int PX Remit</label>
    <nameField>
        <displayFormat>RE-{00000000}</displayFormat>
        <label>Int PX Remint Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int PX Remit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PNC_Recon_Batch__c/PNC_Recon_Batch__c.object-meta.xml
<CustomObject>
    <label>PNC Recon Batch</label>
    <nameField>
        <label>PNC Recon Header Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PNC Recon Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PNC_Recon_Detail__c/PNC_Recon_Detail__c.object-meta.xml
<CustomObject>
    <label>PNC Recon Detail</label>
    <nameField>
        <displayFormat>RECON-{00000000}</displayFormat>
        <label>PNC Recon Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PNC Recon Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PNC_Recon_Detail__c/fields/Biller_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Biller_Account_Number__c</fullName>
    <label>Biller Account Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PNC_Recon_Detail__c/fields/Capture_Date__c.field-meta.xml
<CustomField>
    <fullName>Capture_Date__c</fullName>
    <label>Capture Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PNC_Recon_Detail__c/fields/Confirmation_Number__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_Number__c</fullName>
    <label>Confirmation Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PNC_Recon_Detail__c/fields/Fee__c.field-meta.xml
<CustomField>
    <fullName>Fee__c</fullName>
    <label>Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PNC_Recon_Detail__c/fields/Int_PX_Remit__c.field-meta.xml
<CustomField>
    <fullName>Int_PX_Remit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Int PX Remit</label>
    <referenceTo>Int_PX_Remit__c</referenceTo>
    <relationshipLabel>PNC Recon Details</relationshipLabel>
    <relationshipName>PNC_Recon_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PNC_Recon_Detail__c/fields/Invoice_Payment__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Payment__c</fullName>
    <label>Invoice Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PNC_Recon_Detail__c/fields/Payment_Channel__c.field-meta.xml
<CustomField>
    <fullName>Payment_Channel__c</fullName>
    <label>Payment Channel</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PNC_Recon_Detail__c/fields/PNC_Recon_Batch__c.field-meta.xml
<CustomField>
    <fullName>PNC_Recon_Batch__c</fullName>
    <label>PNC Recon Batch</label>
    <referenceTo>PNC_Recon_Batch__c</referenceTo>
    <relationshipLabel>PNC Recon Details</relationshipLabel>
    <relationshipName>PNC_Recon_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PNC_Recon_Detail__c/fields/Processing_Date__c.field-meta.xml
<CustomField>
    <fullName>Processing_Date__c</fullName>
    <label>Processing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PNC_Recon_Detail__c/fields/Reversal_Amount__c.field-meta.xml
<CustomField>
    <fullName>Reversal_Amount__c</fullName>
    <label>Reversal Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PNC_Recon_Detail__c/fields/Reversal_Reason__c.field-meta.xml
<CustomField>
    <fullName>Reversal_Reason__c</fullName>
    <label>Reversal Reason</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Reconciler.cls
/**************************************************************************************************************
*
*  Reconciler - compares a pnc reciept file to cloud lending
*
*  log:
*
* 	5/9/19 - MRM Created Class 
*
****************************************************************************************************************/
global class Reconciler implements Messaging.InboundEmailHandler {
    
    String finalEmailTextBody;
    String fromAddress;
    Boolean attachment = false;
    List<String> lineList = new List<String>();
    Integer linesSubmitted = 0;
    List<PNC_Recon_Detail__c> insertList = new List<PNC_Recon_Detail__c>();
    ID reconBatchId;

    //*********************************
    //* handleInboundEmail
    //********************************* 
     
    
    /**************************************************************************
    *HANDEL INBOUND EMAIL
    **************************************************************************/
    global Messaging.InboundEmailResult handleInboundEmail(Messaging.InboundEmail email, Messaging.InboundEnvelope envelope) {
       
        Boolean emailSent = false; 
        finalEmailTextBody = 'Your detailed results....\n\n';
        fromAddress = email.fromAddress;
        Messaging.InboundEmailResult result = new Messaging.InboundEmailresult();
        system.debug(email);
        system.debug(envelope);

        system.debug(email.binaryAttachments); 

        Messaging.InboundEmail.BinaryAttachment[] bAttachments = email.BinaryAttachments; 
        

        if (email.binaryAttachments != null && email.binaryAttachments.size() > 0)
            attachment = true;
        else{
            sendShortEmail('Missing Attachment; Try again!');
            return result;
        }

        String theBody = bAttachments[0].body.toString();
        system.debug(theBody);
            
        //validEmail checks for some standard items before processing  
        if (attachment){
          	lineList = theBody.split('\n',0); //tab attachment format
        }
        else  
          	lineList = theBody.split('\n\n',0);  //microsoft outlook format
            
        ID hId = createHeader();

        Integer i = 0;  
        for (String s:lineList){
        	system.debug('line is:' + i + s);
          	s = s.replace('\n','');
            	
           	List <String> fieldList = new List<String>();
               	
            fieldList = s.split(',',-1);
               		
           	system.debug('field list size is:' + fieldList.size());
                	
           	system.debug('id is:' + fieldList[0]); 
            if (fieldList[0] == 'ACH-CCD'){
                createDetail(hId,fieldList);
                linesSubmitted++;
            }

          	i++;	
        }//end for loop linelist
            	
        insert insertList;
        
        List<PNC_Recon_Detail__c> checklist = new List<PNC_Recon_Detail__c>();
        checklist = [select invoice_number__c
                    ,Invoice_Payment__c
                    ,Confirmation_number__c
                    ,Int_PX_Remit__r.name
                    ,status__c
                    from PNC_Recon_Detail__c
                    where  pnc_recon_batch__c = :reconBatchId
                    order by invoice_number__c
                    ]; 

        if (!emailSent){ //send final email
        	
            finalEmailTextBody += standardEmailText();

            finalEmailTextBody += 'Invoice' + '\t\t\t' + 'Payment' + '\t' + 
                'Confirmation Nbr' + '\t' + 'Matched To' + '\t'  +  'Status' + '\n';

            Integer total = 0;
            Integer ok = 0;
            Integer failures = 0;

            total = checkList.size();

            for (PNC_Recon_Detail__c r:checkList){
                if (r.status__c == 'OK')
                    ok++;
                else
                    failures++;    
                
                String message = '';

                if (r.int_px_remit__r.name == null)
                    message = 'No Match';
                else {
                    message = r.int_px_remit__r.name;
                }

                finalEmailTextBody += r.invoice_number__c + '\t' + r.invoice_payment__c + '\t\t' + 
                r.confirmation_number__c + '\t\t' + message + '\t'  +  r.status__c + '\n';
            }
        	
            finalEmailTextBody += '\n\nTotal Number of Records: ' + total + '\n';
            finalEmailTextBody += 'Total Number OK: ' + ok + '\n';
            finalEmailTextBody += 'Total Number of Mismatches: ' + failures + '\n';

            sendShortEmail(finalEmailTextBody);
        }
        
        return result;
    }
    
    /**************************************************************************
    *CREATE HEADER
    **************************************************************************/
        ID createHeader(){

        PNC_Recon_Batch__c h = new PNC_Recon_Batch__c();
        h.name = string.valueOf(DateTime.now());
        insert h;
        reconBatchId = h.id;

        return h.id;

    } 
    
    /**************************************************************************
    *CREATE DETAIL
    **************************************************************************/
    void  createDetail(ID h, List<String> fieldList ){

        PNC_Recon_Detail__c d = new PNC_Recon_Detail__c();
         
        d.pnc_recon_batch__c = h;
        d.Payment_Method__c = fieldList[0];
        d.Payment_Channel__c = fieldList[1];
        d.Processing_Date__c = date.parse(fieldList[2]);
        d.Capture_Date__c = date.parse(fieldList[3]);
        d.Biller_Account_Number__c = fieldList[4];
        d.Invoice_Number__c = fieldList[5];
        d.Account_Name__c = fieldList[6];
        Integer i = 8;
        if (fieldList[6].contains('"')){
            i = 8; 
        }
        else {
            i = 7;
        }
        if (fieldList[i] != null)
            d.Invoice_Payment__c = decimal.valueOf(fieldList[i]);

         if (fieldList[i+1] != null)
            d.Reversal_Amount__c = decimal.valueOf(fieldList[i+1]);


        d.Confirmation_Number__c = fieldList[i+2];
        d.Reversal_Reason__c = fieldList[i+3];

        system.debug(fieldList[i+4]);
        if (fieldList[i+4] == '0')
            if (fieldList[i+4] == '0')
                d.fee__c = 0;
            else
                d.Fee__c = decimal.valueOf(fieldList[i+4]);

        insertList.add(d);
    
    }
    
    
    /**************************************************************************
    * SENDSHORTEMAIL 
    *
    * this sends the user an email with a special error message
    *
    ***************************************************************************/
    public void sendShortEmail(String msg){
        
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        OrgWideEmailAddress o = [select id, address from OrgWideEmailAddress where displayName = 'NewCo Customer Service'];

        mail.setOrgWideEmailAddressId(o.id);

        String[] toAddress = new String[] {fromAddress};
        
        mail.setToAddresses(toAddress);
        
        mail.setSubject('Recon Results');
        
        mail.setBccSender(false);
     
        mail.setPlainTextBody(msg);

        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
           
    }
    
    
    
    /****************************************************************************
    *STANDARD TEXT
    *
    * standard email text
    *
    ****************************************************************************/
    public String standardEmailText(){
    	
    	String finalEmailTextBody = '';
    	
    	
    	return finalEmailTextBody;
    }
   
}