force-app/main/default/objects/Lease_Claims__c/Lease_Claims__c.object-meta.xml
<CustomObject>
    <label>Lease Claim</label>
    <nameField>
        <displayFormat>CL# {YYYY}{MM}{000000}</displayFormat>
        <label>Lease Claims Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lease Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lease_Claims__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Lease Claims</relationshipLabel>
    <relationshipName>Lease_Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lease_Claims__c/fields/Claim_Status__c.field-meta.xml
<CustomField>
    <fullName>Claim_Status__c</fullName>
    <label>Claim Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Customer Contacted</fullName>
            </value>
            <value>
                <fullName>Pending - Waiting on Claim</fullName>
            </value>
            <value>
                <fullName>Pending - Waiting on Customer</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Pending - Waiting on Vendor Install</fullName>
                <isActive>false</isActive>
                <label>Pending - Waiting on Vendor Install</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lease_Claims__c/fields/Customer_Rep_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Rep_Phone_Number__c</fullName>
    <label>Customer Rep Phone Number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lease_Claims__c/fields/Lease__c.field-meta.xml
<CustomField>
    <fullName>Lease__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lease</label>
    <referenceTo>cllease__Lease_Account__c</referenceTo>
    <relationshipLabel>Lease Claims</relationshipLabel>
    <relationshipName>Lease_Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestIC.cls
@isTest
public  class TestIC {
    static TestMethod void Test1() {

        cllease__Lease_Account__c l = TestHelper.createContract();
        Lease_Claims__c claim = new Lease_Claims__c();
        String notes='Hello';
        List<String> eList = new List<String>();

        Lease_Claims__c c = new Lease_Claims__c();
        
        c.lease__c = l.id;
        c.Account__c = l.cllease__account__c;
        c.Claim_Status__c = 'New';
        c.Customer_Rep_Phone_Number__c = '9005551212';
        
        List<cllease__Contract_Equipment__c> eList2 = new List<cllease__Contract_Equipment__c>();
        eList2 = [select id from cllease__Contract_Equipment__c where cllease__Contract__c = :l.id];
        for (cllease__Contract_Equipment__c e:eList2)
            eList.add(e.id);
    
        ICNewClaim.createClaim(l.id, c, eList, notes);

        ICNewClaim.getLease(l.id);

        ICNewClaim.save(l.id,eList);
    }
    

    static TestMethod void Test2() {

        cllease__Lease_Account__c l = TestHelper.createContract();
        Lease_Claims__c claim = new Lease_Claims__c();
        String notes='Hello';
        List<String> eList = new List<String>();

        Lease_Claims__c c = new Lease_Claims__c();
        
        c.lease__c = l.id;
        c.Account__c = l.cllease__account__c;
        c.Claim_Status__c = 'New';
        c.Customer_Rep_Phone_Number__c = '9005551212';
        insert c;


    
        

        ICNewEquipment.getLease(c.id);

        ICNewEquipment.save(c.id,eList);

        ICNewEquipment.getEquipment(c.id);
    }

    static TestMethod void Test3() {

        cllease__Lease_Account__c l = TestHelper.createContract();
        Lease_Claims__c claim = new Lease_Claims__c();
        String notes='Hello';
        List<String> eList = new List<String>();

        Lease_Claims__c c = new Lease_Claims__c();
        
        c.lease__c = l.id;
        c.Account__c = l.cllease__account__c;
        c.Claim_Status__c = 'New';
        c.Customer_Rep_Phone_Number__c = '9005551212';
        insert c;


    
        

        IC_ClaimNotesController.getDocuments(l.id);

        IC_ClaimNotesController.uploadAttachment(l.id, 'test.txt', 'contentType','base64Body');
		
    }
}